In [1]:
# ENV["PYTHON"] = "/home/users/kww231/virtualenvs/phd/bin/python"
# rm(Pkg.dir("PyCall","deps","PYTHON")); Pkg.checkout("PyCall"); Pkg.build("PyCall")

include("../src/obs_funcs.jl")
include("../src/mod_funcs.jl")

massbincounts

In [2]:
# here are the HOD parameters to be used for each of the samples

# for the -18 magnitude threshold, parameters are taken from Table 3 in Zehavi et al. 2011
m_th_18 = -18.0
paramdict_18 = Dict("alpha" => 1.04,
                    "logM0" =>  9.81,
                    "logM1" => 12.42,
                    "logMmin" => 11.18,
                    "sigma_logM" => 0.19)

# for the -19 magnitude threshold, parameters are taken from Sinha et al. 2016 best-fit values
# from table 3, using the values for Planck Cosmology with Mvir (as Chinchilla halos are defined) and no PCA uncertainties
m_th_19 = -19.0
paramdict_19 = Dict("alpha" => 0.95,       #  1.02 in Zehavi    1.03 in Zentner
                    "logM0" => 11.14,      #  9.77
                    "logM1" => 12.80,      # 12.63             12.78 whether I use Zehavi M0 or not
                    "logMmin" => 11.58,    # 11.45             11.72
                    "sigma_logM" => 0.05)  #  0.19              0.70

# for the -20 magnitude threshold, parameters are taken from Table 2 of Zentner et al. 2016, using M_0 from Zehavi
m_th_20 = -20.0
paramdict_20 = Dict("alpha" => 1.16,       #  1.0 in Zehavi
                    "logM0" =>  12.35,
                    "logM1" => 13.23,      # 12.98
                    "logMmin" => 11.96,    # 11.83
                    "sigma_logM" => 0.38)  #  0.25

m_th_arr = [m_th_18, m_th_19, m_th_20]
paramdicts = [paramdict_18, paramdict_19, paramdict_20]

3-element Array{Dict{String,Float64},1}:
 Dict("sigma_logM"=>0.19,"logMmin"=>11.18,"alpha"=>1.04,"logM1"=>12.42,"logM0"=>9.81) 
 Dict("sigma_logM"=>0.05,"logMmin"=>11.58,"alpha"=>0.95,"logM1"=>12.8,"logM0"=>11.14) 
 Dict("sigma_logM"=>0.38,"logMmin"=>11.96,"alpha"=>1.16,"logM1"=>13.23,"logM0"=>12.35)

In [27]:
# set which sample to generate a mock for and grab the data
sample_num = 3
datdf, vols = load_groupdat(sample_num, quenform = "both")

(47784×46 DataFrames.DataFrame. Omitted printing of 39 columns
│ Row   │ foo    │ galid  │ groupid │ cenid  │ rband    │ Psat │ Mh         │
├───────┼────────┼────────┼─────────┼────────┼──────────┼──────┼────────────┤
│ 1     │ PROB10 │ 3      │ 26747   │ 3      │ -20.9869 │ 0.0  │ 3.03811e12 │
│ 2     │ PROB10 │ 17     │ 46451   │ 17     │ -20.4593 │ 0.0  │ 1.67686e12 │
│ 3     │ PROB10 │ 21     │ 29108   │ 21     │ -21.3315 │ 0.0  │ 2.77697e12 │
│ 4     │ PROB10 │ 53     │ 15187   │ 53     │ -21.1077 │ 0.0  │ 5.48889e12 │
│ 5     │ PROB10 │ 81     │ 36849   │ 81     │ -20.5768 │ 0.0  │ 2.15532e12 │
│ 6     │ PROB10 │ 83     │ 24536   │ 83     │ -20.8211 │ 0.0  │ 3.32973e12 │
│ 7     │ PROB10 │ 85     │ 52256   │ 85     │ -20.6159 │ 0.0  │ 1.47419e12 │
│ 8     │ PROB10 │ 90     │ 25369   │ 90     │ -20.8662 │ 0.0  │ 3.21402e12 │
│ 9     │ PROB10 │ 93     │ 10451   │ 93     │ -21.3781 │ 0.0  │ 7.98381e12 │
│ 10    │ PROB10 │ 112    │ 1095    │ 112    │ -21.8533 │ 0.0  │ 4.79077e13 │
│

In [28]:
# get another dataframe of just the quenched galaxies and their masses for counting quenched fraction
quendf = datdf[datdf[:Dn4000] .> 1.6, [:log10M]]

38107×1 DataFrames.DataFrame
│ Row   │ log10M  │
├───────┼─────────┤
│ 1     │ 10.512  │
│ 2     │ 10.3666 │
│ 3     │ 10.6508 │
│ 4     │ 10.4301 │
│ 5     │ 10.5335 │
│ 6     │ 10.5255 │
│ 7     │ 10.7409 │
│ 8     │ 10.9336 │
│ 9     │ 10.452  │
│ 10    │ 10.3502 │
│ 11    │ 10.5326 │
⋮
│ 38096 │ 10.5386 │
│ 38097 │ 10.351  │
│ 38098 │ 10.4875 │
│ 38099 │ 10.3127 │
│ 38100 │ 10.4342 │
│ 38101 │ 10.3453 │
│ 38102 │ 10.3944 │
│ 38103 │ 10.5359 │
│ 38104 │ 10.4333 │
│ 38105 │ 10.887  │
│ 38106 │ 10.8045 │
│ 38107 │ 10.5835 │

In [29]:
# generate the mock galaxies
mockgals = get_mock(paramdicts[sample_num], m_th_arr[sample_num], 3)

383665×6 Array{Float64,2}:
 1.62049e9   23.8908   178.352   69.3618  1.0   4.0
 1.62049e9   54.2385   147.212   86.2612  1.0   4.0
 1.62057e9   17.5035   142.147  121.991   1.0   4.0
 1.62057e9   30.9299   185.085  119.293   1.0   4.0
 1.62057e9    3.68962  147.032  121.787   1.0   4.0
 1.61988e9   46.9333   134.869   85.5845  1.0   4.0
 1.62057e9   10.0025   186.166  128.661   1.0   4.0
 1.62111e9   39.2183   196.085   89.3759  1.0   4.0
 1.62049e9   38.9772   181.184   67.3124  1.0   4.0
 1.62049e9   28.9453   165.548   72.4649  1.0   4.0
 1.6205e9    55.9567   140.022   83.2813  1.0   4.0
 1.62057e9   62.4508   162.055  106.218   1.0   4.0
 1.62057e9   20.3627   143.978  122.714   1.0   4.0
 ⋮                                              ⋮  
 1.63305e9  252.357    357.58   257.892   0.0  17.0
 1.63305e9  224.616    362.029  263.523   0.0  17.0
 1.63237e9  237.126    349.875  237.058   0.0  17.0
 1.63298e9  238.778    398.423  221.981   0.0  17.0
 1.63298e9  238.291    374.415  255.4

In [30]:
# compute the environment densities of the galaxies in the mock
deltas = get_rho(mockgals[:, 2:4], 400.0, 10.0)

383665-element Array{Float64,1}:
 2.66376 
 2.82305 
 0.274351
 0.194704
 0.433645
 1.86729 
 0.274351
 1.46906 
 0.274351
 0.911527
 2.34517 
 0.632763
 0.393822
 ⋮       
 4.2567  
 0.513292
 0.154881
 1.46906 
 2.74341 
 1.708   
 1.78764 
 3.06199 
 2.66376 
 2.62394 
 3.14164 
 2.10623 

In [7]:
# grab the halos to get stellar masses
halodf = load_halodat()

1875265×26 DataFrames.DataFrame. Omitted printing of 20 columns
│ Row     │ halo_id    │ halo_upid │ x       │ y       │ z       │ vx      │
├─────────┼────────────┼───────────┼─────────┼─────────┼─────────┼─────────┤
│ 1       │ 1620490488 │ -1        │ 23.8908 │ 178.352 │ 71.8972 │ 254.19  │
│ 2       │ 1620489517 │ -1        │ 54.2385 │ 147.212 │ 83.8446 │ 132.18  │
│ 3       │ 1620568787 │ -1        │ 17.5035 │ 142.147 │ 121.233 │ 206.25  │
│ 4       │ 1620569234 │ -1        │ 30.9299 │ 185.085 │ 116.149 │ 100.4   │
│ 5       │ 1620569405 │ -1        │ 3.68962 │ 147.032 │ 119.642 │ 318.78  │
│ 6       │ 1619882298 │ -1        │ 46.9333 │ 134.869 │ 85.2907 │ -32.87  │
│ 7       │ 1620570495 │ -1        │ 10.0025 │ 186.166 │ 125.959 │ 173.74  │
│ 8       │ 1621113337 │ -1        │ 39.2183 │ 196.085 │ 87.0058 │ -92.91  │
│ 9       │ 1620494893 │ -1        │ 38.9772 │ 181.184 │ 67.201  │ -119.43 │
│ 10      │ 1620494673 │ -1        │ 28.9453 │ 165.548 │ 73.521  │ 28.3    │
│ 11      │ 1620495423 │ -1        │ 55.9567 │ 140.022 │ 85.7931 │ -53.57  │
⋮
│ 1875254 │ 1633037941 │ -1        │ 247.842 │ 363.894 │ 258.432 │ 584.4   │
│ 1875255 │ 1633039302 │ -1        │ 259.414 │ 399.276 │ 260.807 │ -651.61 │
│ 1875256 │ 1633049894 │ -1        │ 222.806 │ 375.506 │ 256.465 │ -704.42 │
│ 1875257 │ 1633052058 │ -1        │ 229.784 │ 381.151 │ 265.435 │ -186.15 │
│ 1875258 │ 1633059693 │ -1        │ 208.309 │ 358.898 │ 261.616 │ 269.29  │
│ 1875259 │ 1633065798 │ -1        │ 258.554 │ 356.669 │ 259.318 │ -527.16 │
│ 1875260 │ 1633066256 │ -1        │ 265.983 │ 361.787 │ 256.26  │ -461.04 │
│ 1875261 │ 1633067144 │ -1        │ 209.721 │ 392.869 │ 265.84  │ -306.17 │
│ 1875262 │ 1633067372 │ -1        │ 211.413 │ 385.231 │ 265.947 │ 28.06   │
│ 1875263 │ 1633067388 │ -1        │ 240.285 │ 395.969 │ 255.802 │ -90.78  │
│ 1875264 │ 1633067471 │ -1        │ 214.532 │ 359.643 │ 258.233 │ 185.14  │
│ 1875265 │ 1633067812 │ -1        │ 207.811 │ 370.363 │ 255.956 │ 414.53  │

In [31]:
# make a merged dataframe of galaxies and halos
mockdf = DataFrame(delta = deltas, halo_id = mockgals[:, 1], subvol = mockgals[:, 6])

# keep only the central galaxies
mockdf = mockdf[mockgals[:, 5] .== 1, :]

# merge with the halos on halo_id
mockdf = join(mockdf, halodf, on = :halo_id)

311248×28 DataFrames.DataFrame. Omitted printing of 22 columns
│ Row    │ delta     │ halo_id   │ subvol │ halo_upid │ x       │ y       │
├────────┼───────────┼───────────┼────────┼───────────┼─────────┼─────────┤
│ 1      │ 2.66376   │ 1.62049e9 │ 4.0    │ -1        │ 23.8908 │ 178.352 │
│ 2      │ 2.82305   │ 1.62049e9 │ 4.0    │ -1        │ 54.2385 │ 147.212 │
│ 3      │ 0.274351  │ 1.62057e9 │ 4.0    │ -1        │ 17.5035 │ 142.147 │
│ 4      │ 0.194704  │ 1.62057e9 │ 4.0    │ -1        │ 30.9299 │ 185.085 │
│ 5      │ 0.433645  │ 1.62057e9 │ 4.0    │ -1        │ 3.68962 │ 147.032 │
│ 6      │ 1.86729   │ 1.61988e9 │ 4.0    │ -1        │ 46.9333 │ 134.869 │
│ 7      │ 0.274351  │ 1.62057e9 │ 4.0    │ -1        │ 10.0025 │ 186.166 │
│ 8      │ 1.46906   │ 1.62111e9 │ 4.0    │ -1        │ 39.2183 │ 196.085 │
│ 9      │ 0.274351  │ 1.62049e9 │ 4.0    │ -1        │ 38.9772 │ 181.184 │
│ 10     │ 0.911527  │ 1.62049e9 │ 4.0    │ -1        │ 28.9453 │ 165.548 │
│ 11     │ 2.34517   │ 1.6205e9  │ 4.0    │ -1        │ 55.9567 │ 140.022 │
⋮
│ 311237 │ 1.30976   │ 1.6329e9  │ 17.0   │ -1        │ 208.164 │ 398.962 │
│ 311238 │ 1.74782   │ 1.63246e9 │ 17.0   │ -1        │ 254.399 │ 350.729 │
│ 311239 │ -0.08406  │ 1.63291e9 │ 17.0   │ -1        │ 245.343 │ 397.768 │
│ 311240 │ 2.18588   │ 1.63299e9 │ 17.0   │ -1        │ 208.177 │ 375.856 │
│ 311241 │ 0.234528  │ 1.6329e9  │ 17.0   │ -1        │ 216.377 │ 373.276 │
│ 311242 │ -0.323001 │ 1.63291e9 │ 17.0   │ -1        │ 244.349 │ 382.835 │
│ 311243 │ -0.641589 │ 1.63299e9 │ 17.0   │ -1        │ 249.434 │ 354.533 │
│ 311244 │ 5.65052   │ 1.63299e9 │ 17.0   │ -1        │ 223.319 │ 366.071 │
│ 311245 │ 0.632763  │ 1.63291e9 │ 17.0   │ -1        │ 234.333 │ 383.227 │
│ 311246 │ 3.34076   │ 1.63304e9 │ 17.0   │ -1        │ 204.754 │ 399.477 │
│ 311247 │ 1.19029   │ 1.63306e9 │ 17.0   │ -1        │ 243.279 │ 385.696 │
│ 311248 │ 0.95135   │ 1.63246e9 │ 17.0   │ -1        │ 223.735 │ 349.279 │

In [32]:
# now to add galaxy stellar masses according to the best fit stellar mass halo mass relation
ths = [18, 19, 20]

# read in the parameters
th = ths[sample_num]
params = squeeze(readdlm("../dat/optim/M$(@sprintf("%d", th))_mass_pars.dat"), 2)

# add stellar mass to dataframe
mockdf[:stelM] = gen_mstars(Array(mockdf[:Mpeak]), Array(mockdf[:Mbar]), params, fix_sig = false)

# and add log stellar mass
mockdf[:log10M] = log10.(mockdf[:stelM])

311248-element Array{Float64,1}:
 10.1213 
 10.1378 
  9.58766
  9.27448
  9.69037
 10.0152 
  9.59987
  9.77239
 10.2787 
 10.5755 
 10.1182 
  9.5999 
  9.16873
  ⋮      
  9.15838
  8.85897
  9.27235
  9.39619
  8.83858
  8.30013
  8.87814
  8.67135
  9.25434
  8.80469
  8.4353 
  8.69023

In [33]:
# set the mass ranges to restrict to for each sample
massmins = [9.4, 9.8, 10.3]
massmaxs = [9.8, 10.3, 11.0]

# keep only the centrals within the massrange of interest for the modeling
mockdf = mockdf[massmins[sample_num] .<= mockdf[:log10M] .< massmaxs[sample_num], :]
datdf = datdf[massmins[sample_num] .<= datdf[:log10M] .< massmaxs[sample_num], :]

47784×46 DataFrames.DataFrame. Omitted printing of 39 columns
│ Row   │ foo    │ galid  │ groupid │ cenid  │ rband    │ Psat │ Mh         │
├───────┼────────┼────────┼─────────┼────────┼──────────┼──────┼────────────┤
│ 1     │ PROB10 │ 3      │ 26747   │ 3      │ -20.9869 │ 0.0  │ 3.03811e12 │
│ 2     │ PROB10 │ 17     │ 46451   │ 17     │ -20.4593 │ 0.0  │ 1.67686e12 │
│ 3     │ PROB10 │ 21     │ 29108   │ 21     │ -21.3315 │ 0.0  │ 2.77697e12 │
│ 4     │ PROB10 │ 53     │ 15187   │ 53     │ -21.1077 │ 0.0  │ 5.48889e12 │
│ 5     │ PROB10 │ 81     │ 36849   │ 81     │ -20.5768 │ 0.0  │ 2.15532e12 │
│ 6     │ PROB10 │ 83     │ 24536   │ 83     │ -20.8211 │ 0.0  │ 3.32973e12 │
│ 7     │ PROB10 │ 85     │ 52256   │ 85     │ -20.6159 │ 0.0  │ 1.47419e12 │
│ 8     │ PROB10 │ 90     │ 25369   │ 90     │ -20.8662 │ 0.0  │ 3.21402e12 │
│ 9     │ PROB10 │ 93     │ 10451   │ 93     │ -21.3781 │ 0.0  │ 7.98381e12 │
│ 10    │ PROB10 │ 112    │ 1095    │ 112    │ -21.8533 │ 0.0  │ 4.79077e13 │
│ 11    │ PROB10 │ 148    │ 33928   │ 148    │ -20.8174 │ 0.0  │ 2.35621e12 │
⋮
│ 47773 │ PROB10 │ 558933 │ 29489   │ 558933 │ -20.7718 │ 0.0  │ 2.73853e12 │
│ 47774 │ PROB10 │ 558934 │ 55804   │ 558934 │ -20.3751 │ 0.0  │ 1.37168e12 │
│ 47775 │ PROB10 │ 558942 │ 36316   │ 558942 │ -20.4865 │ 0.0  │ 2.18968e12 │
│ 47776 │ PROB10 │ 558953 │ 50049   │ 558953 │ -20.4489 │ 0.0  │ 1.54558e12 │
│ 47777 │ PROB10 │ 558957 │ 42020   │ 558957 │ -20.4118 │ 0.0  │ 1.86992e12 │
│ 47778 │ PROB10 │ 558968 │ 24316   │ 558968 │ -20.7879 │ 0.0  │ 3.36167e12 │
│ 47779 │ PROB10 │ 558972 │ 36434   │ 558972 │ -20.5877 │ 0.0  │ 2.18195e12 │
│ 47780 │ PROB10 │ 558974 │ 51357   │ 558974 │ -21.291  │ 0.0  │ 1.50256e12 │
│ 47781 │ PROB10 │ 558994 │ 5549    │ 558994 │ -21.683  │ 0.0  │ 1.42019e13 │
│ 47782 │ PROB10 │ 558998 │ 7936    │ 558998 │ -21.4794 │ 0.0  │ 1.03407e13 │
│ 47783 │ PROB10 │ 559009 │ 20070   │ 559009 │ -21.1309 │ 0.0  │ 4.11373e12 │
│ 47784 │ PROB10 │ 559026 │ 43108   │ 559026 │ -20.5571 │ 0.0  │ 1.81875e12 │

In [34]:
# shift the environment densities to match those of the data, in case of difference
logdeltas = log10.(mockdf[:delta] + 1)
deltamean = mean(logdeltas)
deltavar = var(logdeltas)
println("       ", "data", "    |    ", "mock")
println("means: ", mean(datdf[:logρ]), " | ", deltamean)
println("devs:  ", sqrt(var(datdf[:logρ])), " | ", sqrt(deltavar))
renormed = (logdeltas - deltamean) / sqrt(deltavar)
mockdf[:delta] = sqrt(var(datdf[:logρ])) * renormed + mean(datdf[:logρ])

       data    |    mock
means: 0.13237964711138933 | 0.1846097498643532
devs:  0.36766927055337684 | 0.31137488085175424


101807-element Array{Float64,1}:
  0.246646 
  0.402123 
 -0.0878743
  0.287693 
 -0.130633 
  0.0846726
  0.0846726
 -0.029758 
  0.287693 
  0.126845 
 -0.0117628
  0.61788  
 -0.177285 
  ⋮        
  0.901144 
  0.527482 
  0.533623 
  0.886016 
 -1.02764  
  0.612674 
  0.508603 
  0.297461 
  0.126845 
 -0.256335 
  0.652915 
  0.224821 

In [36]:
# now to get the mock numbers to match the quenched fraction in the data
nqbins = [10, 20, 20]  # number of mass bins to use for the quenched fraction

# get the massbins for computing quenched fraction
quenmasses = linspace(massmins[sample_num], massmaxs[sample_num], nqbins[sample_num] + 1)

# compute fractions for the data
qfracs = zeros(nqbins[sample_num])
for j in 1:nqbins[sample_num]
    ntot = size(datdf[quenmasses[j] .<= datdf[:log10M] .< quenmasses[j + 1], :])[1]
    nquens = size(quendf[quenmasses[j] .<= quendf[:log10M] .< quenmasses[j + 1], :])[1]
    qfracs[j] = nquens / ntot
    println(ntot)
end
println(qfracs)
    
mockdf = get_quenfrac(mockdf, quenmasses, qfracs)

5164
4979
4704
4233
4049
3622
3256
3001
2660
2397
1934
1618
1371
1168
980
837
625
505
388
293
[0.660922, 0.6905, 0.718537, 0.737302, 0.767597, 0.784373, 0.816339, 0.852716, 0.876316, 0.876095, 0.91727, 0.932633, 0.92779, 0.932363, 0.960204, 0.965352, 0.9648, 0.972277, 0.987113, 0.982935]


81678×30 DataFrames.DataFrame. Omitted printing of 24 columns
│ Row   │ delta     │ halo_id   │ subvol │ halo_upid │ x       │ y       │
├───────┼───────────┼───────────┼────────┼───────────┼─────────┼─────────┤
│ 1     │ -0.130633 │ 1.63526e9 │ 23.0   │ -1        │ 335.486 │ 194.784 │
│ 2     │ 0.126845  │ 1.62664e9 │ 7.0    │ -1        │ 120.988 │ 293.416 │
│ 3     │ 0.912934  │ 1.62574e9 │ 15.0   │ -1        │ 147.633 │ 174.91  │
│ 4     │ 0.190236  │ 1.62066e9 │ 5.0    │ -1        │ 96.3887 │ 153.813 │
│ 5     │ -0.108808 │ 1.63367e9 │ 21.0   │ -1        │ 307.776 │ 43.6341 │
│ 6     │ 0.11317   │ 1.62173e9 │ 4.0    │ -1        │ 69.0045 │ 260.789 │
│ 7     │ 0.694705  │ 1.63148e9 │ 16.0   │ -1        │ 245.737 │ 311.761 │
│ 8     │ 0.514974  │ 1.63319e9 │ 27.0   │ -1        │ 298.32  │ 399.108 │
│ 9     │ 0.685709  │ 1.61899e9 │ 2.0    │ -1        │ 70.9309 │ 15.578  │
│ 10    │ 0.61788   │ 1.61974e9 │ 3.0    │ -1        │ 55.3104 │ 72.7393 │
│ 11    │ -0.130633 │ 1.62717e9 │ 16.0   │ -1        │ 189.194 │ 339.008 │
⋮
│ 81667 │ -0.508883 │ 1.63543e9 │ 23.0   │ -1        │ 345.801 │ 162.896 │
│ 81668 │ 0.26758   │ 1.62954e9 │ 12.0   │ -1        │ 242.353 │ 106.449 │
│ 81669 │ -0.256335 │ 1.63237e9 │ 17.0   │ -1        │ 238.27  │ 339.307 │
│ 81670 │ 0.643147  │ 1.63403e9 │ 20.0   │ -1        │ 350.035 │ 50.0171 │
│ 81671 │ 0.316456  │ 1.63108e9 │ 23.0   │ -1        │ 296.295 │ 222.147 │
│ 81672 │ -0.130633 │ 1.63627e9 │ 24.0   │ -1        │ 335.198 │ 218.226 │
│ 81673 │ 0.440127  │ 1.6332e9  │ 27.0   │ -1        │ 276.25  │ 364.355 │
│ 81674 │ -0.740666 │ 1.62443e9 │ 11.0   │ -1        │ 181.087 │ 104.252 │
│ 81675 │ 0.307046  │ 1.62626e9 │ 14.0   │ -1        │ 187.281 │ 246.065 │
│ 81676 │ 1.14366   │ 1.6326e9  │ 16.0   │ -1        │ 213.23  │ 330.359 │
│ 81677 │ 0.21355   │ 1.63025e9 │ 13.0   │ -1        │ 258.463 │ 191.181 │
│ 81678 │ 0.425262  │ 1.63253e9 │ 18.0   │ -1        │ 223.076 │ 324.889 │

In [37]:
# finally leave only the relevant columns in the mock for modeling and save to disk
mockdf = mockdf[:, [:halo_id, :halo_mvir, :halo_rvir, :halo_nfw_conc, :halo_spin, :halo_mz_05, :halo_mz_1,
                    :logMh, :logMpeak, :delta, :stelM, :log10M, :subvol]]
outfile = "../dat/mocks/M$(@sprintf("%d", th))_cenquen_mock.csv"
CSV.write(outfile, mockdf)

CSV.Sink{Void,DataType}(    CSV.Options:
        delim: ','
        quotechar: '"'
        escapechar: '\\'
        missingstring: ""
        dateformat: nothing
        decimal: '.'
        truestring: 'true'
        falsestring: 'false'
        internstrings: true, IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1), "../dat/mocks/M20_cenquen_mock.csv", 114, true, String["halo_id", "halo_mvir", "halo_rvir", "halo_nfw_conc", "halo_spin", "halo_mz_05", "halo_mz_1", "logMh", "logMpeak", "delta", "stelM", "log10M", "subvol"], 13, false, Val{false})