In [1]:
include("/home/kilian/wrk/assbiass/src/obs_funcs.jl")
include("/home/kilian/wrk/assbiass/src/mod_funcs.jl")

INFO: Checking out PyCall master...
INFO: Pulling PyCall latest master...
INFO: No packages to install, update or remove
INFO: Building Conda
INFO: Building PyCall
Info: PyCall is using /home/kilian/.envs/astro3/bin/python (Python 3.6.6) at /home/kilian/.envs/astro3/bin/python, libpython = /usr/lib/libpython3.6m
Info: /home/kilian/.playground/share/assbiass/packages/v0.6/PyCall/deps/deps.jl has not changed
Info: /home/kilian/.playground/share/assbiass/packages/v0.6/PyCall/deps/PYTHON has been updated


massbincounts

In [2]:
# here are the HOD parameters to be used for each of the samples

# for the -18 magnitude threshold, parameters are taken from Table 3 in Zehavi et al. 2011
m_th_18 = -18.0
paramdict_18 = Dict("alpha" => 1.04,
                    "logM0" =>  9.81,
                    "logM1" => 12.42,
                    "logMmin" => 11.18,
                    "sigma_logM" => 0.19)

# for the -19 magnitude threshold, parameters are taken from Sinha et al. 2016 best-fit values
# from table 3, using the values for Planck Cosmology with Mvir (as Chinchilla halos are defined) and no PCA uncertainties
m_th_19 = -19.0
paramdict_19 = Dict("alpha" => 0.95,       #  1.02 in Zehavi    1.03 in Zentner
                    "logM0" => 11.14,      #  9.77
                    "logM1" => 12.80,      # 12.63             12.78 whether I use Zehavi M0 or not
                    "logMmin" => 11.58,    # 11.45             11.72
                    "sigma_logM" => 0.05)  #  0.19              0.70

# for the -20 magnitude threshold, parameters are taken from Table 2 of Zentner et al. 2016, using M_0 from Zehavi
m_th_20 = -20.0
paramdict_20 = Dict("alpha" => 1.16,       #  1.0 in Zehavi
                    "logM0" =>  12.35,
                    "logM1" => 13.23,      # 12.98
                    "logMmin" => 11.96,    # 11.83
                    "sigma_logM" => 0.38)  #  0.25

m_th_arr = [m_th_18, m_th_19, m_th_20]
paramdicts = [paramdict_18, paramdict_19, paramdict_20]

3-element Array{Dict{String,Float64},1}:
 Dict("sigma_logM"=>0.19,"logMmin"=>11.18,"alpha"=>1.04,"logM1"=>12.42,"logM0"=>9.81) 
 Dict("sigma_logM"=>0.05,"logMmin"=>11.58,"alpha"=>0.95,"logM1"=>12.8,"logM0"=>11.14) 
 Dict("sigma_logM"=>0.38,"logMmin"=>11.96,"alpha"=>1.16,"logM1"=>13.23,"logM0"=>12.35)

In [3]:
# set which sample to generate a mock for and grab the data
sample_num = 1
datdf, vols = load_groupdat(sample_num, quenform = "both")

(12208×46 DataFrames.DataFrame. Omitted printing of 39 columns
│ Row   │ foo    │ galid  │ groupid │ cenid  │ rband    │ Psat │ Mh         │
├───────┼────────┼────────┼─────────┼────────┼──────────┼──────┼────────────┤
│ 1     │ PROB10 │ 17     │ 2485    │ 17     │ -20.4593 │ 0.0  │ 1.5053e12  │
│ 2     │ PROB10 │ 22     │ 13924   │ 22     │ -19.4819 │ 0.0  │ 2.20027e11 │
│ 3     │ PROB10 │ 83     │ 824     │ 83     │ -20.8211 │ 0.0  │ 4.7694e12  │
│ 4     │ PROB10 │ 93     │ 607     │ 93     │ -21.3781 │ 0.0  │ 6.43239e12 │
│ 5     │ PROB10 │ 99     │ 11864   │ 99     │ -18.7129 │ 0.0  │ 2.64106e11 │
│ 6     │ PROB10 │ 164    │ 10733   │ 164    │ -20.0047 │ 0.0  │ 2.95793e11 │
│ 7     │ PROB10 │ 181    │ 6630    │ 181    │ -19.6391 │ 0.0  │ 5.08768e11 │
│ 8     │ PROB10 │ 195    │ 12160   │ 195    │ -18.9404 │ 0.0  │ 2.56719e11 │
│ 9     │ PROB10 │ 205    │ 7018    │ 205    │ -19.8112 │ 0.0  │ 4.77532e11 │
│ 10    │ PROB10 │ 209    │ 8375    │ 209    │ -19.7289 │ 0.0  │ 3.91487e11 │
│

In [4]:
# get another dataframe of just the quenched galaxies and their masses for counting quenched fraction
quendf = datdf[datdf[:Dn4000] .> 1.6, [:log10M]]

5638×1 DataFrames.DataFrame
│ Row  │ log10M  │
├──────┼─────────┤
│ 1    │ 10.3666 │
│ 2    │ 10.5335 │
│ 3    │ 10.7409 │
│ 4    │ 9.60447 │
│ 5    │ 10.5326 │
│ 6    │ 10.3271 │
│ 7    │ 9.54054 │
│ 8    │ 10.251  │
│ 9    │ 9.80124 │
│ 10   │ 9.94717 │
│ 11   │ 10.2012 │
⋮
│ 5627 │ 9.99146 │
│ 5628 │ 10.0807 │
│ 5629 │ 10.1406 │
│ 5630 │ 10.0861 │
│ 5631 │ 10.0627 │
│ 5632 │ 10.2088 │
│ 5633 │ 10.0591 │
│ 5634 │ 10.1331 │
│ 5635 │ 10.3165 │
│ 5636 │ 9.82801 │
│ 5637 │ 9.72783 │
│ 5638 │ 10.3453 │

In [5]:
# generate the mock galaxies
nside = 3  # number of subvolumes per side of cube to compute jackknife errors later
mockgals = get_mock(paramdicts[sample_num], m_th_arr[sample_num], nside)

1832182×5 Array{Float64,2}:
 1.62049e9   23.8908   178.352   69.3618  1.0
 1.62049e9   54.2385   147.212   86.2612  1.0
 1.62057e9   17.5035   142.147  121.991   1.0
 1.62057e9   30.9299   185.085  119.293   1.0
 1.62057e9    3.68962  147.032  121.787   1.0
 1.61988e9   46.9333   134.869   85.5845  1.0
 1.62057e9   10.0025   186.166  128.661   1.0
 1.62111e9   39.2183   196.085   89.3759  1.0
 1.62049e9   38.9772   181.184   67.3124  1.0
 1.62049e9   28.9453   165.548   72.4649  1.0
 1.6205e9    55.9567   140.022   83.2813  1.0
 1.62057e9   62.4508   162.055  106.218   1.0
 1.62057e9   20.3627   143.978  122.714   1.0
 ⋮                                           
 1.63291e9  217.366    391.477  211.086   0.0
 1.63299e9  244.322    354.392  238.514   0.0
 1.63298e9  221.873    373.901  252.498   0.0
 1.63299e9  258.998    358.065  259.844   0.0
 1.63246e9  253.761    351.039  264.374   0.0
 1.63236e9  206.285    343.378  235.826   0.0
 1.63238e9  249.434    337.411  199.124   0.0
 1.632

In [6]:
# compute the environment densities of the galaxies in the mock
deltas = get_rho(mockgals[:, 2:4], 400.0, 10.0)

1832182-element Array{Float64,1}:
  2.47743  
  2.51079  
  0.209179 
  0.20084  
  0.492711 
  1.52677  
  0.384302 
  1.06811  
  0.184162 
  0.834617 
  2.20224  
  0.392641 
  0.267554 
  ⋮        
  5.34611  
 -0.524667 
  3.86174  
  2.4274   
  1.63518  
  6.33013  
 -0.39958  
  0.0674136
  2.36068  
  1.39334  
  2.16054  
  2.01044  

In [7]:
# grab the halos to get stellar masses
halodf = load_halodat()

1875265×26 DataFrames.DataFrame. Omitted printing of 20 columns
│ Row     │ halo_id    │ halo_upid │ x       │ y       │ z       │ vx      │
├─────────┼────────────┼───────────┼─────────┼─────────┼─────────┼─────────┤
│ 1       │ 1620490488 │ -1        │ 23.8908 │ 178.352 │ 71.8972 │ 254.19  │
│ 2       │ 1620489517 │ -1        │ 54.2385 │ 147.212 │ 83.8446 │ 132.18  │
│ 3       │ 1620568787 │ -1        │ 17.5035 │ 142.147 │ 121.233 │ 206.25  │
│ 4       │ 1620569234 │ -1        │ 30.9299 │ 185.085 │ 116.149 │ 100.4   │
│ 5       │ 1620569405 │ -1        │ 3.68962 │ 147.032 │ 119.642 │ 318.78  │
│ 6       │ 1619882298 │ -1        │ 46.9333 │ 134.869 │ 85.2907 │ -32.87  │
│ 7       │ 1620570495 │ -1        │ 10.0025 │ 186.166 │ 125.959 │ 173.74  │
│ 8       │ 1621113337 │ -1        │ 39.2183 │ 196.085 │ 87.0058 │ -92.91  │
│ 9       │ 1620494893 │ -1        │ 38.9772 │ 181.184 │ 67.201  │ -119.43 │
│ 10      │ 1620494673 │ -1        │ 28.9453 │ 165.548 │ 73.521  │ 28.3    │
│ 11      │ 1620495423 │ -1        │ 55.9567 │ 140.022 │ 85.7931 │ -53.57  │
⋮
│ 1875254 │ 1633037941 │ -1        │ 247.842 │ 363.894 │ 258.432 │ 584.4   │
│ 1875255 │ 1633039302 │ -1        │ 259.414 │ 399.276 │ 260.807 │ -651.61 │
│ 1875256 │ 1633049894 │ -1        │ 222.806 │ 375.506 │ 256.465 │ -704.42 │
│ 1875257 │ 1633052058 │ -1        │ 229.784 │ 381.151 │ 265.435 │ -186.15 │
│ 1875258 │ 1633059693 │ -1        │ 208.309 │ 358.898 │ 261.616 │ 269.29  │
│ 1875259 │ 1633065798 │ -1        │ 258.554 │ 356.669 │ 259.318 │ -527.16 │
│ 1875260 │ 1633066256 │ -1        │ 265.983 │ 361.787 │ 256.26  │ -461.04 │
│ 1875261 │ 1633067144 │ -1        │ 209.721 │ 392.869 │ 265.84  │ -306.17 │
│ 1875262 │ 1633067372 │ -1        │ 211.413 │ 385.231 │ 265.947 │ 28.06   │
│ 1875263 │ 1633067388 │ -1        │ 240.285 │ 395.969 │ 255.802 │ -90.78  │
│ 1875264 │ 1633067471 │ -1        │ 214.532 │ 359.643 │ 258.233 │ 185.14  │
│ 1875265 │ 1633067812 │ -1        │ 207.811 │ 370.363 │ 255.956 │ 414.53  │

In [8]:
# make a merged dataframe of galaxies and halos
mockdf = DataFrame(delta = deltas, halo_id = mockgals[:, 1], subvol = mockgals[:, 6])

# keep only the central galaxies
mockdf = mockdf[mockgals[:, 5] .== 1, :]

# merge with the halos on halo_id
mockdf = join(mockdf, halodf, on = :halo_id)

1092171×27 DataFrames.DataFrame. Omitted printing of 21 columns
│ Row     │ delta      │ halo_id   │ halo_upid │ x       │ y       │ z       │
├─────────┼────────────┼───────────┼───────────┼─────────┼─────────┼─────────┤
│ 1       │ 2.47743    │ 1.62049e9 │ -1        │ 23.8908 │ 178.352 │ 71.8972 │
│ 2       │ 2.51079    │ 1.62049e9 │ -1        │ 54.2385 │ 147.212 │ 83.8446 │
│ 3       │ 0.209179   │ 1.62057e9 │ -1        │ 17.5035 │ 142.147 │ 121.233 │
│ 4       │ 0.20084    │ 1.62057e9 │ -1        │ 30.9299 │ 185.085 │ 116.149 │
│ 5       │ 0.492711   │ 1.62057e9 │ -1        │ 3.68962 │ 147.032 │ 119.642 │
│ 6       │ 1.52677    │ 1.61988e9 │ -1        │ 46.9333 │ 134.869 │ 85.2907 │
│ 7       │ 0.384302   │ 1.62057e9 │ -1        │ 10.0025 │ 186.166 │ 125.959 │
│ 8       │ 1.06811    │ 1.62111e9 │ -1        │ 39.2183 │ 196.085 │ 87.0058 │
│ 9       │ 0.184162   │ 1.62049e9 │ -1        │ 38.9772 │ 181.184 │ 67.201  │
│ 10      │ 0.834617   │ 1.62049e9 │ -1        │ 28.9453 │ 165.548 │ 73.521  │
│ 11      │ 2.20224    │ 1.6205e9  │ -1        │ 55.9567 │ 140.022 │ 85.7931 │
⋮
│ 1092160 │ 0.692851   │ 1.63299e9 │ -1        │ 256.803 │ 394.928 │ 229.496 │
│ 1092161 │ 4.07855    │ 1.63238e9 │ -1        │ 212.825 │ 343.387 │ 229.471 │
│ 1092162 │ 3.74499    │ 1.63238e9 │ -1        │ 213.12  │ 352.38  │ 223.081 │
│ 1092163 │ 1.26825    │ 1.63245e9 │ -1        │ 245.222 │ 347.293 │ 254.41  │
│ 1092164 │ -0.407919  │ 1.63246e9 │ -1        │ 215.429 │ 337.562 │ 244.914 │
│ 1092165 │ 0.50939    │ 1.63246e9 │ -1        │ 234.727 │ 351.387 │ 239.967 │
│ 1092166 │ -0.816538  │ 1.63291e9 │ -1        │ 262.43  │ 394.969 │ 205.113 │
│ 1092167 │ 2.11885    │ 1.63297e9 │ -1        │ 212.432 │ 376.051 │ 223.454 │
│ 1092168 │ 1.71857    │ 1.63299e9 │ -1        │ 227.07  │ 357.184 │ 234.368 │
│ 1092169 │ -0.733147  │ 1.63299e9 │ -1        │ 224.269 │ 393.816 │ 235.85  │
│ 1092170 │ -0.0743523 │ 1.63299e9 │ -1        │ 253.26  │ 370.036 │ 240.538 │
│ 1092171 │ 1.15151    │ 1.63306e9 │ -1        │ 225.624 │ 381.025 │ 262.786 │

In [9]:
# now to add galaxy stellar masses according to the best fit stellar mass halo mass relation
ths = [18, 19, 20]

# read in the parameters
th = ths[sample_num]
params = squeeze(readdlm("../dat/optim/M$(@sprintf("%d", th))_mass_pars.dat"), 2)

# add stellar mass to dataframe
mockdf[:stelM] = gen_mstars(Array(mockdf[:Mpeak]), Array(mockdf[:Mbar]), params, fix_sig = false)

# and add log stellar mass
mockdf[:log10M] = log10.(mockdf[:stelM])

1092171-element Array{Float64,1}:
 10.7137 
 10.5356 
 10.4582 
 10.5707 
 10.5787 
 10.5075 
 10.7739 
 10.8607 
 10.6994 
 10.6661 
 10.6098 
 10.3536 
 10.5007 
  ⋮      
  8.78117
  8.79027
  9.08589
  8.68751
  9.28203
  8.94705
  8.62243
  9.25397
  8.81968
  8.68443
  8.61701
  9.00021

In [10]:
# now to get the mock numbers to match the quenched fraction in the data
nqbins = 20  # number of mass bins to use for the quenched fraction
massmins = [9.4, 9.8, 10.3]

# keep only the centrals within the massrange of interest for the modeling
mockdf = mockdf[massmins[sample_num] .<= mockdf[:log10M] .< 11.0, :]
    
# get the massbins for computing quenched fraction
quenmasses = linspace(massmins[sample_num], 11.0, nqbins + 1)

# compute fractions for the data
qfracs = zeros(nqbins)
for j in 1:nqbins
    ntot = size(datdf[quenmasses[j] .<= datdf[:log10M] .< quenmasses[j + 1], :])[1]
    nquens = size(quendf[quenmasses[j] .<= quendf[:log10M] .< quenmasses[j + 1], :])[1]
    qfracs[j] = nquens / ntot
end
println(qfracs)
    
mockdf = get_quenfrac(mockdf, quenmasses, qfracs)

[0.110749, 0.147558, 0.157205, 0.239595, 0.293044, 0.331203, 0.394505, 0.466238, 0.594438, 0.642308, 0.670851, 0.788976, 0.830986, 0.876543, 0.897833, 0.936255, 0.950311, 1.0, 0.983333, 1.0]

340299×29 DataFrames.DataFrame. Omitted printing of 23 columns
│ Row    │ delta     │ halo_id   │ halo_upid │ x       │ y       │ z       │
├────────┼───────────┼───────────┼───────────┼─────────┼─────────┼─────────┤
│ 1      │ -0.449615 │ 1.61861e9 │ -1        │ 1.84362 │ 10.4189 │ 55.185  │
│ 2      │ -0.624737 │ 1.63092e9 │ -1        │ 204.002 │ 234.466 │ 103.23  │
│ 3      │ -0.166083 │ 1.62097e9 │ -1        │ 2.01861 │ 150.445 │ 375.889 │
│ 4      │ -0.649755 │ 1.62619e9 │ -1        │ 128.428 │ 234.462 │ 180.198 │
│ 5      │ 1.83532   │ 1.62597e9 │ -1        │ 170.705 │ 237.079 │ 2.87335 │
│ 6      │ 2.7693    │ 1.62036e9 │ -1        │ 24.6398 │ 132.684 │ 359.48  │
│ 7      │ -0.441276 │ 1.62444e9 │ -1        │ 171.35  │ 94.9889 │ 246.349 │
│ 8      │ 0.0257177 │ 1.63231e9 │ -1        │ 257.206 │ 315.865 │ 152.035 │
│ 9      │ 0.951365  │ 1.62453e9 │ -1        │ 156.752 │ 73.4321 │ 291.893 │
│ 10     │ 0.259214  │ 1.63772e9 │ -1        │ 370.215 │ 360.958 │ 83.2546 │
│ 11     │ 0.417659  │ 1.62513e9 │ -1        │ 134.649 │ 110.501 │ 291.781 │
⋮
│ 340288 │ 0.117449  │ 1.62786e9 │ -1        │ 149.309 │ 357.998 │ 64.791  │
│ 340289 │ 0.30091   │ 1.63771e9 │ -1        │ 370.195 │ 388.981 │ 97.1363 │
│ 340290 │ 0.142466  │ 1.63305e9 │ -1        │ 217.141 │ 396.841 │ 289.805 │
│ 340291 │ 1.46839   │ 1.62725e9 │ -1        │ 195.47  │ 308.547 │ 68.8027 │
│ 340292 │ 0.409319  │ 1.63619e9 │ -1        │ 378.108 │ 206.301 │ 350.021 │
│ 340293 │ 2.94443   │ 1.61959e9 │ -1        │ 5.99909 │ 78.0104 │ 272.203 │
│ 340294 │ 0.642816  │ 1.62081e9 │ -1        │ 99.7305 │ 188.978 │ 289.419 │
│ 340295 │ -0.574702 │ 1.61922e9 │ -1        │ 88.9839 │ 91.1746 │ 26.8637 │
│ 340296 │ -0.549685 │ 1.63778e9 │ -1        │ 334.96  │ 371.805 │ 170.807 │
│ 340297 │ 2.7693    │ 1.62502e9 │ -1        │ 121.026 │ 141.901 │ 196.274 │
│ 340298 │ 0.417659  │ 1.61937e9 │ -1        │ 32.5292 │ 49.9072 │ 137.341 │
│ 340299 │ 1.32663   │ 1.63186e9 │ -1        │ 206.434 │ 269.078 │ 257.129 │

In [11]:
# finally leave only the relevant columns in the mock for modeling
mockdf = mockdf[:, [:halo_id, :halo_mvir, :halo_rvir, :halo_nfw_conc, :halo_spin, :halo_mz_05, :halo_mz_1,
                    :delta, :stelM, :log10M]]
outfile = "../dat/mocks/M$(@sprintf("%d", th))_cenquen_mock.csv"
CSV.write(outfile, mockdf)

CSV.Sink{Void,DataType}(    CSV.Options:
        delim: ','
        quotechar: '"'
        escapechar: '\\'
        missingstring: ""
        dateformat: nothing
        decimal: '.'
        truestring: 'true'
        falsestring: 'false'
        internstrings: true, IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1), "../dat/mocks/M18_cenquen_mock.csv", 92, true, String["halo_id", "halo_mvir", "halo_rvir", "halo_nfw_conc", "halo_spin", "halo_mz_05", "halo_mz_1", "delta", "stelM", "log10M"], 10, false, Val{false})